app/controllers/application_controller.rb

カリキュラム
https://master.tech-camp.in/curriculums/2955
RailsアプリケーションにBasic認証を導入しよう
まで完了。
※記述のみ。動作確認はまだ。

Basic認証導入の記述

---

Gemfile
app/controllers/application_controller.rb

Basic認証にまつわる記述、Gemの削除
※自動デプロイ完了後再度実装

Basic認証を一旦取り消す

---

app/assets/javascripts/items.coffee
app/assets/stylesheets/items.scss
app/controllers/items_controller.rb
app/helpers/items_helper.rb
app/views/items/index.html.erb
config/routes.rb
test/controllers/items_controller_test.rb

#WHAT
・本番環境接続確認のための作成
　※今後itemsについてはこれらを編集
・本番環境にビューのレイアウトを適用させる為。
#WHY
・デプロイを可能にする為

items関連ファイル作成・アセットファイルコンパイル

---

config/initializers/carrierwave.rb
config/unicorn.rb

#what
1. コメントアウト部分の有効化
2. unicornの listen 3000 の記述を削除
＃why
carrierwaveのコメントアウト部分を戻し忘れていたので有効にしました。

Megen3104/master 投稿一覧　修正

---

app/assets/stylesheets/identification.scss
app/views/personal_datas/identification.html.haml
config/routes.rb

＃what
identificationへのルーティングを追加。
ビューの修正。
CSS→SCSSに変更。

Mercari 本人確認　修正

---

app/assets/stylesheets/module/header.scss
app/views/items/shared/_header.html.haml

ログイン後のヘッダーを追加

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/credit_card.scss
app/assets/stylesheets/identification.scss
app/assets/stylesheets/method_of_payment.scss
app/assets/stylesheets/module/product-list.scss
app/controllers/personal_datas_controller.rb
app/views/items/index.html.haml
app/views/personal_datas/credit_card.html.haml
app/views/personal_datas/identification.html.haml
app/views/personal_datas/method_of_payment.html.haml
config/routes.rb

#what
　ユーザー支払いページ作成(ビュー)
　クレジットカード登録ページの作成(ビュー)
　コントローラー、ルーティングの追加
　不要なセレクタの削除
　ヘッダー、フッター、サイドバーの追加

Mgen3104/master クレジットカード

---

config/routes.rb

＃what
コンフリクトを起こしたルーティングファイルの訂正

コンフリクトを起こしたルーティングの訂正

---

config/routes.rb

コンフリクトを起こしたルーティング　endの追加

---

app/controllers/users_controller.rb
app/views/users/registration.html.haml
config/routes.rb

新規登録の最初のviewをusersコントローラーに移動

---

app/assets/stylesheets/credit_card.scss
app/assets/stylesheets/identification.scss
app/assets/stylesheets/method_of_payment.scss
app/views/personal_datas/credit_card.html.haml
app/views/personal_datas/identification.html.haml
app/views/personal_datas/method_of_payment.html.haml

#what
ユーザー支払いページ
のCSSを追加
クレジットカード登録ページ
のCSSの追加
重複しているセレクタの修正

Mercari ユーザー支払い＆クレジットカード登録

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/method_of_payment.scss
app/assets/stylesheets/purchase_confirmation.scss
app/controllers/personal_datas_controller.rb
app/views/personal_datas/method_of_payment.html.haml
app/views/personal_datas/purchase_confirmation.html.haml
config/routes.rb

#what
商品購入確認ページのView、CSS、Routing、Controllerの作成
ユーザークレジットカード登録ページ [セレクタの重複の削除]

Mercari 商品購入確認ページ

---

app/assets/stylesheets/identification.scss
app/assets/stylesheets/module/product-list.scss
config/environments/production.rb

Mercari 修正

---

README.md
app/models/brand.rb
app/models/first_category.rb
app/models/item.rb
app/models/second_category.rb
app/models/third_category.rb
db/migrate/20181218064737_create_first_categories.rb
db/migrate/20181218065052_create_second_categories.rb
db/migrate/20181218065949_create_third_categories.rb
db/migrate/20181218070626_create_brands.rb
db/migrate/20181218071026_create_items.rb
db/schema.rb
spec/factories/brands.rb
spec/factories/first_categories.rb
spec/factories/items.rb
spec/factories/second_categories.rb
spec/factories/third_categories.rb
spec/models/brand_spec.rb
spec/models/first_category_spec.rb
spec/models/item_spec.rb
spec/models/second_category_spec.rb
spec/models/third_category_spec.rb

Items、first_category、second_category、third_category、brandテーブルを作成

Itemsテーブル、その他関連テーブル作成

---

app/assets/stylesheets/module/product-list.scss
app/views/items/index.html.haml

Mercari 修正3

---

app/assets/stylesheets/module/product-list.scss
app/controllers/items_controller.rb
app/views/items/index.html.haml

#what
トップページの出品商品一覧の復元
#why
githubの不具合で以前の状態に戻ってしまったため

トップページ商品一覧の復元

---

app/models/brand.rb
app/models/delivery.rb
app/models/first_category.rb
app/models/image.rb
app/models/item.rb
app/models/second_category.rb
app/models/size.rb
app/models/third_category.rb

モデルのアソシエーションが消えてしまったのを修正

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/pankuzu.scss
app/controllers/items_controller.rb
app/views/personal_datas/credit_card.html.haml
app/views/personal_datas/identification.html.haml
app/views/personal_datas/method_of_payment.html.haml

#what
パンくずリストの復元
#why
githubの不具合でコードが以前の状態に戻ってしまったため。

パンくずリストの復元

---

app/assets/stylesheets/search.scss
app/views/items/search.html.haml
app/views/items/shared/_header.html.haml

#what
商品検索Level. 1 の実装
#why
出品商品のあいまい検索をできるようにするため

Mercari 商品検索1

---

app/assets/javascripts/slick.js

トップページのリンクを踏むとカルーセルが機能しなかったのを修正した
ターボリンクスをロードすることで改善した
オートプレイのスピードを遅くした

New carousel

---

app/controllers/items_controller.rb
app/views/items/buy.html.haml

本番環境でpay.jpがAPIキーが違うというエラーが出たので鍵を変更

payjpの公開鍵変更
